import type { GroveSlot } from '../palette.ts'

// A global userstyle for the Stylus extension. Deliberately conservative:
// color-scheme plus the base surfaces, so sites that define their own colors
// mostly win. Extend per-site from here.
export function renderStylus(palette: Record<GroveSlot, string>): string {
  const vars = [
    ['--cinder-background', palette.background],
    ['--cinder-container', palette.container],
    ['--cinder-surface', palette.surface],
    ['--cinder-overlay', palette.overlay],
    ['--cinder-text', palette.text],
    ['--cinder-text-subtle', palette.text_subtle],
    ['--cinder-text-bright', palette.text_bright],
    ['--cinder-accent', palette.primary],
    ['--cinder-error', palette.error],
  ]
    .map(([name, value]) => `    ${name}: ${value};`)
    .join('\n')

  return `/* ==UserStyle==
@name           Cinder Muted
@namespace      github.com/aileks/cinder-muted
@version        1.0.0
@description    Muted ember palette for the web, a monochrome variant of Cinder Grove
@author         Kieran Pedrick <kieran@aileks.dev>
@license        GPL-3.0-or-later
==/UserStyle== */

/* Generated by pnpm build in cinder-muted; do not edit. */

@-moz-document regexp("https?://.*") {
  :root {
    color-scheme: dark !important;
${vars}
  }

  html {
    background-color: var(--cinder-background) !important;
  }

  body {
    background-color: var(--cinder-background);
    color: var(--cinder-text);
  }

  a {
    color: var(--cinder-accent);
  }

  a:visited {
    color: var(--cinder-text-subtle);
  }

  ::selection {
    background-color: var(--cinder-surface);
    color: var(--cinder-text-bright);
  }

  input,
  textarea,
  select {
    background-color: var(--cinder-container);
    color: var(--cinder-text);
    border: 1px solid var(--cinder-overlay);
  }

  button {
    background-color: var(--cinder-container);
    color: var(--cinder-text-bright);
    border: 1px solid var(--cinder-overlay);
  }

  code,
  kbd,
  pre,
  samp {
    background-color: var(--cinder-container);
    color: var(--cinder-text-bright);
  }

  hr {
    border-color: var(--cinder-overlay);
  }
}
`
}
