import type { GroveSlot } from '../palette.ts'
import { applyTones } from './substitute.ts'

export const STYLUS_VERSION = '1.0.0'
const REPO = 'https://github.com/aileks/cinder-muted'

export interface StylusSite {
  slug: string
  name: string
  domains: string[]
  description: string
  // Site-native colors left verbatim: selector attribute values must keep
  // matching the site's markup, and template colors already written as final
  // muted values skip re-substitution.
  nativeColors: string[]
}

export const SITES: StylusSite[] = [
  { slug: 'github', name: 'GitHub', domains: ['github.com', 'gist.github.com'], description: 'GitHub', nativeColors: [] },
  { slug: 'duckduckgo', name: 'DuckDuckGo', domains: ['duckduckgo.com', 'duck.ai', 'start.duckduckgo.com'], description: 'DuckDuckGo search', nativeColors: ['de5833', '5b9e4d', '3ca82b', '4cba3c', '333333'] },
  { slug: 'wikipedia', name: 'Wikipedia', domains: ['wikipedia.org'], description: 'Wikipedia', nativeColors: [] },
  { slug: 'youtube', name: 'YouTube', domains: ['youtube.com'], description: 'YouTube', nativeColors: [] },
  { slug: 'reddit', name: 'Reddit', domains: ['reddit.com', 'old.reddit.com'], description: 'Reddit', nativeColors: [] },
  { slug: 'hacker-news', name: 'Hacker News', domains: ['news.ycombinator.com'], description: 'Hacker News', nativeColors: ['fafaf0', 'f6f6ef', 'ff6600', 'ffffaa', '3c963c', 'ffffff'] },
  { slug: 'lobsters', name: 'Lobsters', domains: ['lobste.rs'], description: 'Lobsters', nativeColors: [] },
  { slug: 'mdn', name: 'MDN', domains: ['developer.mozilla.org', 'interactive-examples.mdn.mozilla.net'], description: 'MDN Web Docs', nativeColors: ['f2ece7', 'dccdc2', 'b09884', '6b5647', '332a24', '221b17', '191412'] },
]

export function renderStylus(palette: Record<GroveSlot, string>): string {
  const vars = [
    ['--cinder-background', palette.background],
    ['--cinder-container', palette.container],
    ['--cinder-surface', palette.surface],
    ['--cinder-overlay', palette.overlay],
    ['--cinder-text', palette.text],
    ['--cinder-text-subtle', palette.text_subtle],
    ['--cinder-text-bright', palette.text_bright],
    ['--cinder-accent', palette.primary],
    ['--cinder-error', palette.error],
  ]
    .map(([name, value]) => `    ${name}: ${value};`)
    .join('\n')

  return `/* ==UserStyle==
@name           Cinder Muted
@namespace      ${REPO}
@version        ${STYLUS_VERSION}
@description    Muted ember palette for the web, a monochrome variant of Cinder Grove
@author         Kieran Pedrick <kieran@aileks.dev>
@license        GPL-3.0-or-later
==/UserStyle== */

/* Generated by pnpm build in cinder-muted; do not edit. */

@-moz-document regexp("https?://.*") {
  :root {
    color-scheme: dark !important;
${vars}
  }

  html {
    background-color: var(--cinder-background) !important;
  }

  body {
    background-color: var(--cinder-background);
    color: var(--cinder-text);
  }

  a {
    color: var(--cinder-accent);
  }

  a:visited {
    color: var(--cinder-text-subtle);
  }

  ::selection {
    background-color: var(--cinder-surface);
    color: var(--cinder-text-bright);
  }

  input,
  textarea,
  select {
    background-color: var(--cinder-container);
    color: var(--cinder-text);
    border: 1px solid var(--cinder-overlay);
  }

  button {
    background-color: var(--cinder-container);
    color: var(--cinder-text-bright);
    border: 1px solid var(--cinder-overlay);
  }

  code,
  kbd,
  pre,
  samp {
    background-color: var(--cinder-container);
    color: var(--cinder-text-bright);
  }

  hr {
    border-color: var(--cinder-overlay);
  }
}
`
}

export function renderStylusSite(
  site: StylusSite,
  template: string,
  tones: Map<string, string>,
): string {
  const domains = site.domains.map((domain) => `domain("${domain}")`).join(', ')
  const preserve = new Set(site.nativeColors)
  const body = applyTones(template, tones, preserve)
  return `/* ==UserStyle==
@name           Cinder Muted - ${site.name}
@namespace      ${REPO}
@version        ${STYLUS_VERSION}
@description    Muted ember ${site.description}, a monochrome variant of Cinder Grove
@author         Kieran Pedrick <kieran@aileks.dev>
@license        GPL-3.0-or-later
@homepageURL    ${REPO}/tree/main/stylus/${site.slug}
@updateURL      https://raw.githubusercontent.com/aileks/cinder-muted/main/stylus/${site.slug}/cinder-muted.user.css
@supportURL     ${REPO}/issues
==/UserStyle== */

/* Generated by pnpm build in cinder-muted; do not edit. */
/* Selectors adapted from catppuccin/userstyles, MIT. */

@-moz-document ${domains} {
${body}
}
`
}
