// Replaces every grove color in a template with its muted tone. Unknown
// colors throw so a grove update with new colors fails the build.

const HEX_RE = /#([0-9A-Fa-f]{8}|[0-9A-Fa-f]{6})(?![0-9A-Fa-f])/g
const ESCAPED_HEX_RE = /%23([0-9A-Fa-f]{6})(?![0-9A-Fa-f])/g
const RGB_RE = /rgb\((\d+) (\d+) (\d+)( ?\/ ?[0-9.]+%?)?\)/g

// `preserve` lists site-native colors (selector attribute values) that must
// stay verbatim for the site's markup to match.
export function applyTones(
  text: string,
  tones: Map<string, string>,
  preserve: ReadonlySet<string> = new Set(),
): string {
  const hexes = text.replace(HEX_RE, (match, digits: string) => {
    if (preserve.has(digits.toLowerCase())) return match
    let tone = tones.get(`#${digits.toLowerCase()}`)
    if (tone !== undefined) return tone

    // Eight digits are ambiguous: bat writes #RRGGBBAA, qt6ct #AARRGGBB. Try
    // both splits and keep the one whose rgb part is a known grove color.
    const suffix = tones.get(`#${digits.slice(0, 6).toLowerCase()}`)
    if (suffix !== undefined) return `#${suffix.slice(1)}${digits.slice(6)}`.toLowerCase()
    const prefix = tones.get(`#${digits.slice(2).toLowerCase()}`)
    if (prefix !== undefined) return `#${digits.slice(0, 2)}${prefix.slice(1)}`.toLowerCase()

    throw new Error(`grove color ${match} is not in the tone map`)
  })

  const escaped = hexes.replace(ESCAPED_HEX_RE, (match, digits: string) => {
    if (preserve.has(digits.toLowerCase())) return match
    const tone = tones.get(`#${digits.toLowerCase()}`)
    if (tone === undefined) throw new Error(`grove color ${match} is not in the tone map`)
    return `%23${tone.slice(1)}`
  })

  return escaped.replace(RGB_RE, (match, r: string, g: string, b: string, alpha?: string) => {
    if (preserve.has(`${r},${g},${b}`)) return match
    const tone = tones.get(`${r},${g},${b}`)
    if (tone !== undefined) {
      const value = tone.slice(1)
      const rgb = [
        parseInt(value.slice(0, 2), 16),
        parseInt(value.slice(2, 4), 16),
        parseInt(value.slice(4, 6), 16),
      ].join(' ')
      return `rgb(${rgb}${alpha ?? ''})`
    }
    if (r === g && g === b && (r === '0' || r === '255')) return match
    throw new Error(`grove rgb(${r} ${g} ${b}) is not in the tone map`)
  })
}

export function rename(text: string, pairs: [string | RegExp, string][]): string {
  return pairs.reduce(
    (result, [from, to]) =>
      typeof from === 'string' ? result.replaceAll(from, to) : result.replace(from, to),
    text,
  )
}

export const GENERATED_NOTE = 'Generated by pnpm build in cinder-muted; do not edit.'
